FRONTENDSCHOOLPLUS2/PickYourPotion

.eslintrc.json
.prettierrc
package-lock.json
package.json
src/app/community/page.tsx
src/app/globals.css
src/app/layout.tsx
tailwind.config.ts

초기 폰트 : font- light
font-light, font-medium, font-bold로 선택하여 사용할 수 있도록 설정했습니다. prettier, eslint 컨벤션 설정했습니다.
#6

init : font 설정,eslint & prettier 컨벤션 설정

---

src/components/layout/Footer.tsx

Footer 컴포넌트 마크업 및 스타일 했습니다
#14

style: Footer 컴포넌트 생성

---

src/app/community/page.tsx
src/app/globals.css
src/components/layout/Footer.tsx
src/components/layout/Header.tsx

술상 커뮤니티 마크업과 스타일 완료했습니다.

---

src/app/(user)/mypage/mypage-button.tsx
src/app/(user)/mypage/mypage-list.tsx
src/app/(user)/mypage/page.tsx
src/components/layout/Header.tsx

style: 마이페이지 스타일 및 마크업

---

src/app/detail/[id]/page.tsx

상품 디테일 페이지 마크업, 스타일링 진행 중입니다.상세 설명,후기 버튼의 스타일링까지 하였습니다.

상품 디테일 페이지 마크업, 스타일링

---

src/app/market/fruit/page.tsx
src/app/market/liquor/page.tsx
src/app/market/raw/page.tsx
src/app/market/refined/page.tsx
src/components/Category.tsx
src/components/VerticalCard.tsx

🎨  verticalCard component 완성

---

src/components/Button.tsx

Style/ljy #31

---

src/app/search/page.tsx

search 폴더를 생성하여 검색 페이지 마크업,스타일링을 완료했습니다.
#40

검색 페이지 마크업,스타일링

---

src/app/(user)/signup/page.tsx
src/app/detail/[id]/detail.tsx
src/app/detail/[id]/detailClient.tsx
src/app/detail/[id]/page.tsx
src/app/detail/[id]/reply.tsx
src/app/detail/[id]/replyItem.tsx

상품 상세 페이지 console 제거, 사용되지 않는 import 제거 했습니다.

상품 상세 페이지 console 제거, 사용되지 않는 import 제거

---

src/app/order/orderCard.tsx

style: OrderCard UI 수정

---

src/app/api/auth/[...nextauth]/route.ts

간편 로그인 400 에러 수정했습니다.
api 폴더 경로를 잘못두어 경로를 재설정했습니다.

[feat]간편 로그인 에러 api 폴더 경로 재설정

---

bruno/PYP/로그인.bru

상세페이지의 이미지를 불러오기, 하단 장바구니와 구매 스타일 조정했습니다.

[feat]상세페이지 이미지 불러오기

---

bruno/PYP/파일 업로드.bru
src/app/admin/page.tsx

✨ feature: 관리자 페이지 상품 등록 기능 구현

---

bruno/PYP/로그인.bru
bruno/PYP/회원 정보 조회.bru
bruno/PYP/회원가입.bru
src/app/(user)/mypage/page.tsx

마이페이지에서 현재 로그인 한 회원정보가 보이도록 했습니당!

Feature/ljy #8

---

package-lock.json
package.json
src/app/detail/[id]/DetailClient.tsx
src/app/detail/[id]/ReplyForm.tsx
src/app/detail/[id]/ReplyItem.tsx
src/app/detail/[id]/page.tsx
src/app/layout.tsx
src/provider/TanstackProvider.tsx
src/zustand/Store.ts

#88 상품 후기 작성까지 하였고, 눌렀을 때 작성한 댓글이 바로 확인되도록 바꾸겠습니다.

[feat] 상품 후기 작성

---

next.config.js
src/app/landing/page.tsx
src/app/landing/setCookie.ts

[Feat] 홈 접속시 술BTI로 리다이렉션, 다시 보지 않기 기능 구현

---

src/app/fonts.ts
src/app/globals.css
src/app/landing/Splash.tsx
src/app/landing/page.tsx
tailwind.config.ts

[Refactor] 스플래시 컴포넌트에 클린업함수 추가

---

src/app/detail/[id]/DetailClient.tsx
src/app/detail/[id]/Reply.tsx
src/app/detail/[id]/ReplyForm.tsx
src/app/detail/[id]/ReplyItem.tsx
src/app/detail/[id]/page.tsx
src/app/layout.tsx

상품 후기 작성 완료하였습니다.
현재는 상품을 불러올 때 들어있는 후기를 사용하였는데 
후기만 불러오는 통신을 한 번 더 하여 후기만 가져와서 보여주는 방법도 있어서 의논하고 싶습니다.
후기 작성하고 새로고침이 안된 이유는 상품을 불러올 때도 tanstack-query를 사용하고 같은 쿼리키로  
```
queryClient.invalidateQueries({
queryKey: ["detail", id],
});
```
등록해주었습니다.

[Feat]상품 후기 post

---

src/app/landing/[result]/page.tsx
src/app/landing/page.tsx
src/app/landing/setCookie.ts
src/components/LinkButton.tsx

[Bug] 검사 후 쇼핑몰이동 버튼 버그 수정 #104

---

package-lock.json
package.json
src/app/detail/[id]/Buying.tsx
src/app/detail/[id]/DetailClient.tsx

상품 구매하기 버튼의 이벤트로 토스페이 테스트 창을 연동하였습니다. 
PortOne의 라이브러리를 team-mintc에서 @portone/browser-sdk로 바꾸었습니다. 
이유는 team-mintc 라이브러리는 개인이 만들어 배포한 라이브러리였고,
공식 라이브러리인 @portone/browser-sdk로 바꾸었습니다.
다음으로 실제 결제가 되도록 구현하겠습니다.

[Feat]상품 구매 토스페이 연동

---

src/app/landing/[result]/Detail.tsx
src/components/DegreeBar.tsx

[Refactor] 검사결과의 degree bar 컴포넌트 분리생성 #108

---

src/api/auth/[...nextauth]/route.ts
src/app/detail/[id]/Buying.tsx
src/app/detail/[id]/DetailClient.tsx

상품 상세페이지의 결제를 portone의 토스 페이먼츠로 연동하여 더미 결제하기를 완료하였습니다.
다음으로 간편 로그인을 완료하여 db에 등록 후 로그인 하였을 때의 id값을 가져와 결제하기를 하겠습니다.

[Feat]상품 상세 더미 결제

---

package-lock.json
package.json
src/app/(user)/login/page.tsx
src/auth.ts
src/types/user.ts

case문에 discord를 추가하여 로그인하면 db에 저장,로그인 페이지 변경했습니다.

[fix] 로그인 db 회원 저장

---

bruno/PYP/장바구니 상품 조회(로그인).bru
bruno/PYP/장바구니 상품 추가.bru
src/app/detail/[id]/AddCart.tsx
src/app/detail/[id]/DetailClient.tsx

장바구니 버튼 이벤트로 토큰이 있으면 장바구니에 상품을 담고 토큰이 없다면 로그인 페이지로 이동하도록 하였습니다. #88

[Feat] 장바구니 버튼 이벤트 추가

---

src/app/Banner.tsx
src/app/globals.css

[style] 메인 이벤트배너 swiper pagination 설정 #111

---

src/app/detail/[id]/DetailClient.tsx
src/app/globals.css
src/zustand/Store.ts

상품 상세 zustand 상태 저장, 디자인 변경 #88

[Feat] 상품 상세의 상태 저장, 디자인 변경

---

package-lock.json
package.json
src/app/detail/[id]/Buying.tsx
src/app/detail/[id]/DetailClient.tsx
src/app/detail/[id]/Reply.tsx
src/app/detail/[id]/ReplyForm.tsx
src/app/globals.css
src/components/InputError.tsx

[style]상품 상세 디자인 변경

---

package-lock.json
src/app/CardItemSmall.tsx
src/app/search/page.tsx
src/app/search/useDebounce.ts
src/components/Input.tsx
src/model/action/userAction.ts

검색 페이지의 검색 창에 상품명을 입력하면 렌더링되도록 구현하였습니다.
#142

[Feat] 검색 페이지 구현

---

src/app/CardSwiper.tsx
src/app/globals.css
src/app/page.tsx
src/components/ProductCard.tsx

메인페이지 자잘한 버그들을 수정했습니다
close #141

[Refactor] 메인페이지 버그 수정

---

src/app/detail/[id]/DetailClient.tsx
src/app/detail/[id]/ReplyItem.tsx
src/app/pay/OrderedCard.tsx
src/zustand/Store.ts

새로고침하면 데이터가 휘발되어 상품 정보 전역 상태 퍼시스트로 세션에 저장했습니다

[Feat]상품 정보 세션에 저장

---

src/app/detail/[id]/DetailClient.tsx

switch case 문으로 카테고리 코드를 주종 텍스트로 변경하였습니다.

[Feat] 카테고리 코드별 주종 적용

---

src/app/detail/[id]/DetailClient.tsx
src/app/search/fetchSearch.ts
src/app/search/page.tsx

Type error: Page "src/app/search/page.tsx" does not match the required types of a Next.js Page.
"fetchSearch" is not a valid Page export field.
Error: Command "npm run build" exited with 1

[fix]배포 오류 푸시

---

src/app/adult/page.tsx

[style] 성인인증 관련 모달 스타일 변경 #131

---

src/app/(user)/mypage/MyPageButton.tsx
src/app/(user)/mypage/MyPageList.tsx
src/app/(user)/mypage/activity/WrittenReviewDetail.tsx
src/app/CardItemSmall.tsx
src/app/detail/[id]/Buying.tsx
src/app/detail/[id]/DetailClient.tsx
src/app/globals.css
src/app/pay/page.tsx
src/app/pay/payments/route.ts
src/app/search/page.tsx
src/components/Card.tsx
src/components/OrderDetail.tsx
src/components/layout/Header.tsx
src/zustand/Store.ts

콘솔에 나오는 image 경고들을 제거하였고, search 페이지 딜레이 시간을 증가시켜서 통신을 적게하도록 바꾸었습니다.

[Fix] 콘솔 경고 제거, search 페이지 딜레이 시간 증가

---

src/app/detail/[id]/Detail.tsx
src/app/detail/[id]/DetailClient.tsx
src/app/globals.css

상품 상세 페이지 고정 너비 삭제, 구매 장바구니 버튼 밑 불투명 스타일 짙게 변경했습니다.

[Style]상품 상세 페이지 고정 너비 삭제, 구매 장바구니 버튼 밑 불투명 스타일 짙게 변경

---

src/app/detail/[id]/Buying.tsx
src/app/detail/[id]/NoReply.tsx
src/app/detail/[id]/Reply.tsx
src/app/detail/[id]/ReplyForm.tsx

구매 목록 조회 통신으로 구매한 목록을 가져와 상품의 아이디와 비교하여 있으면 
후기 폼 렌더링을 없으면 후기 폼 렌더링이 되지 않도록 구현했습니다.
작성된 후기의 length가 0이면 후기가 없다는 표시를 구현했습니다.

상품 구매한 회원에게만 후기 폼 렌더링, 작성된 후기가 없으면 후기 없다는 표시 구현

---

src/app/(user)/mypage/MyPageList.tsx
src/app/CardItemSmall.tsx
src/app/detail/[id]/Detail.tsx
src/app/detail/[id]/DetailClient.tsx
src/app/order/Empty.tsx
src/app/search/page.tsx

검색 페이지의 초기 상품 결과를 5개로 limit하였고, 스타일 fix 했습니다.

[Fix] 검색 초기 페이지 상품 결과 5개 제한

---

src/app/ChannelTalkManager.tsx
src/app/layout.tsx

[Bug] 로그아웃 상태에서 주문정보 찾지 못해 생기는 오류 수정#177

---

src/app/detail/[id]/AddCart.tsx
src/app/detail/[id]/Buying.tsx
src/app/detail/[id]/Detail.tsx
src/app/detail/[id]/ReplyForm.tsx
src/app/loading.tsx

로딩이 아주 짧을 경우 이미지가 나오는 것은 산만하다고 생각하여 0.2초간 setTimeOut을 주어 페이지 이동을 할 때 0.2초 흰 화면을 보여주고 로딩 이미지가 나오도록 수정했습니다.
alert으로 사용하던 안내를 Toast로 변경하였습니다.

[Fix]로딩 타이머 추가, alert을 Toast로 변경

---

src/app/adult/page.tsx
src/app/cart/CartPage.tsx

[Feature] 장바구니에서 결제하기 버튼 클릭시 성인인증 로직 구현 #131

---

src/app/detail/[id]/AddCart.tsx
src/app/detail/[id]/Buying.tsx
src/components/ProductCard.tsx

- alert으로 들어간 로직들을 토스트 메세지로 수정하였습니다.
- 몇몇 토스트 메세지 문구를 변경하였습니다.
- 토스트 메세지를 각 상황에 맞게 info->error, error->info로 수정하였습니다.

[Fix] Toast 메세지 수정

---

bruno/PYP/상품 목록 조회.bru
src/app/detail/[id]/NoReview.tsx
src/app/pay/payments/route.ts
src/app/search/page.tsx

사용자가 결제 중 취소할 경우 보던 상품의 상세 페이지로 이동하도록 수정했습니다.

[Fix]사용자 결제 취소시 상품 상세 페이지로 이동

---

src/app/(user)/login/page.tsx
src/auth.ts
src/model/action/userAction.ts

env로 숨겨놓은 아이디와 비밀번호로 로그인하도록 구현하였습니다.

[Feat] 체험용 로그인 버튼 구현

---

src/app/brewery/page.tsx
src/app/cart/CartPage.tsx
src/app/cart/page.tsx
src/app/cart/pay/PayPage.tsx
src/app/cart/pay/page.tsx
src/app/detail/[id]/AddCart.tsx
src/app/market/layout.tsx
src/components/CartCard.tsx
src/zustand/Store.ts

서버 사이드에서 받아오던 fetch Props를 export 해와서 클라이언트 사이드에서 import 해와서 통신하는 방식으로 수정하였고, tanstackQuery를 사용하여 useQuery와useMutation을 사용하였습니다.
useQuery와 useMutation을 사용한 이유는 쿼리키를 맞춰주어 invalidateQueries를 사용하여 상태가 변했을 때 refetch를 하기 위해서 tanstackQuery를 사용했습니다.

[Fix] 장바구니 상품 새로고침해야 렌더링 되는 현상 수정

---

src/app/(user)/login/page.tsx
src/app/market/layout.tsx
src/auth.ts
src/model/action/userAction.ts

next auth의 redirectTo는 로그인 반영이 되지않아 클라이언트 사이드에서 window.location.href로 새로고침을 발생시켜서 수정하였습니다.

[Fix] 체험 로그인 새로고침해야 반영되는 오류

---

src/components/layout/Header.tsx

[Style] landing, admin 페이지 header 숨김처리 #228

---

bruno/PYP/북마크 제거.bru
bruno/PYP/북마크 추가.bru
src/app/detail/[id]/Buying.tsx
src/app/detail/[id]/DetailClient.tsx
src/app/detail/[id]/ReplyForm.tsx
src/app/detail/[id]/page.tsx

상품 상세 페이지에 하트 모양 svg를 생성하여 찜이 된 상품은 분홍 하트를, 찜하지 않은 상품은 회색 하트로 구현하였습니다.

[Feat]상품 찜 기능 구현

---

src/app/globals.css
src/app/layout.tsx

globals.css에 hide-scrollbar 클래스명을 추가하고 layout.tsx에서 사용했습니다.

[Fix] 상품 상세페이지 스크롤 오류 수정

---

src/app/page.tsx
src/components/Card.tsx

[Style] 베스트상품 순위 태그 추가 #212

---

bruno/PYP/주문 목록 조회.bru
src/app/(user)/mypage/MyPageButton.tsx
src/app/bookmark/BookMarkDetail.tsx
src/app/bookmark/BookmarkList.tsx
src/app/bookmark/page.tsx
src/app/detail/[id]/BookMarkButton.tsx
src/app/detail/[id]/DetailClient.tsx
src/components/OrderDetail.tsx

[Feat] 찜한 상품 목록 페이지 구현

---

src/components/Card.tsx

[Style] Card 컴포넌트 순위 태그 rate 값이 있을때만 랜더링되게 수정

---

src/app/(user)/login/FastLogin.tsx
src/app/(user)/login/page.tsx
src/app/adult/action.ts
src/app/cart/CartPage.tsx
src/app/cart/pay/complete/page.tsx
src/app/page.tsx
src/app/pay/complete/page.tsx
src/provider/TanstackProvider.tsx

메인페이지에 접근할 때 체험 로그인의 아이디라면 extra의 isAdult를 false로 변경되도록 구현하였고, 
결제할 때마다 성인인증을 할 수 있습니다.

[Feat]체험 로그인 isAdult 값을 메인 페이지에서 항상 false로 변경되도록 구현

---

bruno/PYP/상품 목록 조회.bru
src/app/search/page.tsx

[Feat] 검색 페이지 paginate 구현

---

src/app/globals.css
src/app/layout.tsx
src/components/CartButton.tsx
src/components/layout/Header.tsx

장바구니가 비어있다 상품이 추가되면 아이콘에 빨간 원이 생기도록 수정하였고, 장바구니가 비워질 때 원이 사라지도록 하였습니다.

[Fix]장바구니 상품 추가 스타일

---

src/app/detail/[id]/ReplyItem.tsx
src/app/globals.css

후기 이미지를 클릭하여 크게 볼 때 이미지 크기를 고정하였고, 닫기 버튼 위치를 고정했습니다.

[Style]후기 이미지 자세히 보기 크기 고정, 닫기 버튼 위치 고정

---

src/app/cart/CartPage.tsx
src/app/cart/cart.ts
src/app/cart/page.tsx
src/app/cart/pay/page.tsx
src/components/CartCard.tsx
src/components/layout/Header.tsx
src/middleware.ts
src/zustand/Store.ts

[Fix]빌드 오류 수정

---

src/app/cart/pay/PayPage.tsx
src/app/pay/page.tsx

데스크톱에서 결제가 완료되었을 때 페이지 이동이 제대로 되지 않아 생긴 오류였습니다.

[Fix] 데스크톱 결제 오류 수정
